version: "3"
services:
  frontend:
    image: brhmkskn/k8sproject_frontend:proje
    ports:
      - 3000:80
  backend:
    image: brhmkskn/k8sproject_backend:proje
    ports:
      - 5000:80
  database:
    image: brhmkskn/k8sproject_database:proje
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_admin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306