apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: brhmkskn/k8sproject_backend:proje

          ports:
            - containerPort: 80

          envFrom:
            - secretRef:
                name: dbsecret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP # The service is accessible only within the Kubernetes cluster. External traffic is routed to this service through the Ingress Controller.
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80